packageExtensions:
  'sst@*':
    dependencies:
      '@aws-sdk/types': '*'
  'sst-aws-cdk@*':
    dependencies:
      '@aws-cdk/cx-api': '*'
      'aws-sdk': '*'
      'fs-extra': '*'
      '@aws-cdk/cloud-assembly-schema': '*'
      '@aws-cdk/cloudformation-diff': '*'
yarnPath: .yarn/releases/yarn-3.3.1.cjs
